create table address_book_entry_seq (next_val bigint);
insert into address_book_entry_seq values ( 1 );
create table address_book (id integer, name varchar(255), primary key (id));
create table address_book_entry (id bigint not null, building_name varchar(255), building_number integer not null, country varchar(255), country_code varchar(255), description varchar(255), email_address varchar(255), full_name varchar(255), line1 varchar(255), line2 varchar(255), line3 varchar(255), phone_number integer not null, postal_code integer not null, address_book_id bigint not null, primary key (id));
create table address_book_entry_seq (next_val bigint);
insert into address_book_entry_seq values ( 1 );
create table address_book (id integer, name varchar(255), primary key (id));
create table address_book_entry (id bigint not null, building_name varchar(255), building_number integer not null, country varchar(255), country_code varchar(255), description varchar(255), email_address varchar(255), full_name varchar(255), line1 varchar(255), line2 varchar(255), line3 varchar(255), phone_number integer not null, postal_code integer not null, address_book_id bigint not null, primary key (id));
create table address_book_entry_seq (next_val bigint);
insert into address_book_entry_seq values ( 1 );
create table address_book (id integer, name varchar(255), primary key (id));
create table address_book_entry (id bigint not null, building_name varchar(255), building_number integer not null, country varchar(255), country_code varchar(255), description varchar(255), email_address varchar(255), full_name varchar(255), line1 varchar(255), line2 varchar(255), line3 varchar(255), phone_number integer not null, postal_code integer not null, address_book_id bigint not null, primary key (id));
create table address_book_entry_seq (next_val bigint);
insert into address_book_entry_seq values ( 1 );
create table address_book (id integer, name varchar(255), primary key (id));
create table address_book_entry (id bigint not null, building_name varchar(255), building_number integer not null, country varchar(255), country_code varchar(255), description varchar(255), email_address varchar(255), full_name varchar(255), line1 varchar(255), line2 varchar(255), line3 varchar(255), phone_number integer not null, postal_code integer not null, address_book_id bigint not null, primary key (id));
create table address_book_entry_seq (next_val bigint);
insert into address_book_entry_seq values ( 1 );
create table address_book (id integer, name varchar(255), primary key (id));
create table address_book_entry (id bigint not null, building_name varchar(255), building_number integer not null, country varchar(255), country_code varchar(255), description varchar(255), email_address varchar(255), full_name varchar(255), line1 varchar(255), line2 varchar(255), line3 varchar(255), phone_number integer not null, postal_code integer not null, address_book_id bigint not null, primary key (id));
create table address_book (id integer, name varchar(255), primary key (id));
create table address_book_entry (id integer, building_name varchar(255), building_number integer not null, country varchar(255), country_code varchar(255), description varchar(255), email_address varchar(255), full_name varchar(255), line1 varchar(255), line2 varchar(255), line3 varchar(255), phone_number integer not null, postal_code integer not null, address_book_id bigint not null, primary key (id));
create table address_book (id integer, name varchar(255), primary key (id));
create table address_book_entry (id integer, building_name varchar(255), building_number integer not null, country varchar(255), country_code varchar(255), description varchar(255), email_address varchar(255), full_name varchar(255), line1 varchar(255), line2 varchar(255), line3 varchar(255), phone_number integer not null, postal_code integer not null, address_book_id bigint not null, primary key (id));
create table address_book (id integer, name varchar(255), primary key (id));
create table address_book_entry (id integer, building_name varchar(255), building_number integer not null, country varchar(255), country_code varchar(255), description varchar(255), email_address varchar(255), full_name varchar(255), line1 varchar(255), line2 varchar(255), line3 varchar(255), phone_number integer not null, postal_code integer not null, address_book_id bigint not null, primary key (id));
create table address_book (id integer, name varchar(255), primary key (id));
create table address_book_entry (id integer, building_name varchar(255), building_number integer not null, country varchar(255), country_code varchar(255), description varchar(255), email_address varchar(255), full_name varchar(255), line1 varchar(255), line2 varchar(255), line3 varchar(255), phone_number integer not null, postal_code integer not null, address_book_id bigint not null, primary key (id));
